### ISSUE TITLE
RC beta 1.4 crashes

### ISSUE THREAD

**Issue by makabar** [johndoh/roundcube-globaladdressbook#46]
if i enable globaladdressbook in plugins array rc14 crashes.
btw. a globaladdressbook with carddav client (for my sabredav) would be great

**Comment by johndoh** [comment]
works for me. please provide more info like whats in the rc error log?

**Comment by johndoh** [comment]
assuming the globaladdressbook is properly enabled in your main rc config (so after you login to rc its listed in the plugins on the about screen) then most likely your problem is:
```php
$config['globaladdressbook_allowed_hosts'] = array('domain.de', 'webmail.domain.de');
```
try removing that line and see if it makes any difference.
the hosts listed in `globaladdressbook_allowed_hosts` should be the IMAP servers that the plugin should be enabled for (assuming you have a multi server setup, else just leave the line out)

**Comment by makabar** [comment]
> $config['globaladdressbook_allowed_hosts'] = array();

rocks! ;-)
Thank You!!!
What do You think about carddav-connector?

**Comment by johndoh** [comment]
I dont have any plans for that. Probably only if support is added to the core.
