### ISSUE TITLE
Question: 3 Group of users with different permissions?

### ISSUE THREAD

**Issue by JMA-Github** [johndoh/roundcube-globaladdressbook#53]
During implementation and testing your plugin, I felt the need for a different handling of permissions:
What I would need are three user groups with the following permissions:
1. Admin with all rights
2. Updaters with $config['globaladdressbook_perms'] = 3;
3. Readers with $config['globaladdressbook_perms'] = 0;

Would it be possible with the actual release?

**Comment by johndoh** [comment]
In the git-master version I've added a plugin hook called `globaladdressbook_permissions` and the idea here is to allow for more granular permission options. I'd prefer to keep the default options simple because once you start going down the groups route then you have issues of group management - its not essentially convenient to update the config file every time you want to change a group memberships and in systems which already have user groups they probably have their own group management stuff in place all ready. With the hook they can interact with their existing group management and then set the permissions at run time. I think it offers more robust solution that trying to define a user group system within the plugin.

The hook can be used from the config file, I added a little tip into the readme with a simple way to do it - you do not need to write an entire plugin to do it.
